# Generated by Django 5.0.4 on 2024-07-04 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("borrower", models.CharField(max_length=100)),
                ("document", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BorrowerSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                ("signature_done", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signed_document",
                    models.FileField(
                        blank=True, null=True, upload_to="signed_documents/"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("x_position", models.IntegerField(default=100)),
                ("y_position", models.IntegerField(default=50)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signature.loanagreement",
                    ),
                ),
            ],
        ),
    ]
