# Generated by Django 5.0.4 on 2024-07-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowersignature",
            name="signed_at",
        ),
        migrations.AlterField(
            model_name="borrowersignature",
            name="mobile_number",
            field=models.IntegerField(max_length=15),
        ),
    ]
