# Generated by Django 5.0.4 on 2024-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signature", "0002_remove_borrowersignature_signed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowersignature",
            name="mobile_number",
            field=models.IntegerField(),
        ),
    ]
